services:
  backend:
    image: ghcr.io/ozeliurs/jellyfier-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/db.sqlite3
    volumes:
      - ./backend:/data
