version: "3.8"

services:
  backend:
    image: ghcr.io/ozeliurs/jellyfier-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./database.db
    volumes:
      - .:/app
